export const actionTypes = {
  OPEN_CART_MODAL: "OPEN_CART_MODAL",
  CLOSE_CART_MODAL: "CLOSE_CART_MODAL",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  DELETE_PRODUCT_IN_CART: "DELETE_PRODUCT_IN_CART",
  INCREASE_PRODUCT_QUANTITY: "INCREASE_PRODUCT_QUANTITY",
};
